### ISSUE TITLE
Create DOCUMENTER_KEY

### ISSUE THREAD

**Issue by DilumAluthge** [cscherrer/SossMLJ.jl#18]
The following steps need to be taken by the owner of the repo (@cscherrer)

1. Use the `DocumenterTools.genkeys()` function (part of the DocumenterTools.jl package) to generate a public key and the corresponding Base64-encoded private key.
2. Create a new GitHub Secret on this repository where the name is `DOCUMENTER_KEY` and the contents are the Base64-encoded private key.
3. Add the public key as a deploy key on this repository. Make sure that the deploy key has write access.

This will enable the documentation to build correctly.

**Comment by cscherrer** [comment]
Thanks for the details @DilumAluthge . I'm not sure if the title of the deploy key is important. I called it `Documenter key`, we can change that if it matter.

I'll close this, we can re-open or start a new issue if docs aren't working.

**Comment by DilumAluthge** [comment]
Yeah the name of the deploy key shouldn't matter.

I'll test now to confirm it's working.
