### ISSUE TITLE
particles

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/SossMLJ.jl#37]
How flexible are MLJ methods? Could we add 

```
function predict_particles(predictor, Xnew)
    args = predictor.args
    pars = particles(predictor.post)
    pred = predictor.pred
    transform = predictor.model.transform
    dist = pred(merge(args, transform(Xnew), pars))
    return particles(dist)
end
```

Example use:
```julia
julia> predict_particles(predictor_joint, X)
(X = [-0.16605238457617638 2.263275565943832 -0.4939955183148124; 1.146316439154414 0.5653810872256257 0.4263891814044257; … ; 0.36542892242375047 1.2784305061990788 -0.424234089042991; 0.18780615955459348 0.7241441456998393 0.07114982679220565],
 σ = 1.0,
 β = Particles{Float64,1000}[0.0707 ± 0.31, -0.112 ± 0.29, 1.87 ± 0.46],
 yhat = Particles{Float64,1000}[-1.19 ± 0.64, 0.817 ± 0.45, -0.426 ± 0.44, 3.04 ± 0.78, -1.78 ± 0.6, -0.129 ± 0.16, 0.456 ± 0.81, -1.36 ± 0.36, -0.913 ± 0.4, 0.0654 ± 0.23],
 y = Particles{Float64,1000}[-1.19 ± 1.2, 0.817 ± 1.1, -0.426 ± 1.1, 3.04 ± 1.3, -1.78 ± 1.2, -0.129 ± 1.0, 0.456 ± 1.3, -1.36 ± 1.0, -0.913 ± 1.1, 0.0654 ± 1.0],)
```

**Comment by DilumAluthge** [comment]
Where does the `predictor_joint` object come from in this case? Is it the result of this?
```julia
predictor_joint = MLJ.predict_joint(mach, X)
```

**Comment by cscherrer** [comment]
Yes, in `mainexample.jl`

**Comment by DilumAluthge** [comment]
What happens if the `X` passed to `MLJ.predict_joint` is a different set of rows than `predictor_joint`.

E.g. suppose that `X_1` and `X_2` are two table with different rows. (Maybe `X_1` is the training set and `X_2` is the testing set.) What happens if we do this:
```julia
predictor_joint = MLJ.predict_joint(mach, X_1)
predict_particles(predictor_joint, X_2)
```

Or this:
```julia
predictor_joint = MLJ.predict_joint(mach, X_2)
predict_particles(predictor_joint, X_1)
```

**Comment by cscherrer** [comment]
```julia
julia> Xnew = (a=randn(3), b=randn(3), c=randn(3))
(a = [-0.04190651918338669, 0.5197194204139544, 1.6375970374945752],
 b = [0.09925549078128458, -2.871307328044467, 1.1713662406149874],
 c = [1.4435780000068634, -0.2702503405373876, 0.6484548153633936],)

julia> predict_particles(predictor_joint, Xnew)
(X = [-0.04190651918338669 0.09925549078128458 1.4435780000068634; 0.5197194204139544 -2.871307328044467 -0.2702503405373876; 1.6375970374945752 1.1713662406149874 0.6484548153633936],
 σ = 1.0,
 β = Particles{Float64,1000}[-0.607 ± 0.35, -2.75 ± 0.3, 3.97 ± 0.43],
 yhat = Particles{Float64,1000}[5.48 ± 0.62, 6.52 ± 0.89, -1.65 ± 0.64],
 y = Particles{Float64,1000}[5.48 ± 1.2, 6.52 ± 1.3, -1.65 ± 1.2],)
```

**Comment by cscherrer** [comment]
Would we need it to return a different type? We could maybe have it default to returning `y`. But I think this function is way useful

**Comment by DilumAluthge** [comment]
So, if I understand correctly, if you do this:
```julia
predictor_joint = MLJ.predict_joint(mach, X_1)
predict_particles(predictor_joint, X_2)
```

The particles you get back correspond to `X_2`, right?

I think that that is the correct behavior. I just wanted to make sure that this was the case.

**Comment by DilumAluthge** [comment]
> Would we need it to return a different type? We could maybe have it default to returning `y`. But I think this function is way useful

Nah I just wanted to make sure the behavior is as I said in my previous comment.

**Comment by DilumAluthge** [comment]
This is very useful. And the best part is that we don't even need to add a new function to MLJ.

That is, the `predict_particles` generic function can live in SossMLJ. I.e. it will be `SossMLJ.predict_particles`.

This is nice because we don't need to make additional changes to MLJ. The only generic function we need to add to MLJ is `MLJModelInterface.predict_joint`. Then, once you get back a `SossMLJPredictor` object, you can do whatever you want with it.

@cscherrer Can you make a PR to add the code for `SossMLJ.predict_particles` to the repo?

**Comment by DilumAluthge** [comment]
Oh wait... it's literally just the function in your first comment, right?

**Comment by cscherrer** [comment]
> The particles you get back correspond to X_2, right?

Yep:
```julia
julia> predictor_joint = SossMLJ.predict_joint(mach, X);

julia> Xnew = (a=randn(3), b=randn(3), c=randn(3));

julia> predict_particles(predictor_joint, Xnew).X == predictor_joint.model.transform(Xnew).X
true
```

> That is, the predict_particles generic function can live in SossMLJ. I.e. it will be SossMLJ.predict_particles.

Ah, right!!

> @cscherrer Can you make a PR to add the code for SossMLJ.predict_particles to the repo?
Yep :)

**Comment by cscherrer** [comment]
> Oh wait... it's literally just the function in your first comment, right?

It will need to change just a bit for namespaces, and we need MonteCarloMeasurements

**Comment by DilumAluthge** [comment]
> > Oh wait... it's literally just the function in your first comment, right?
> 
> It will need to change just a bit for namespaces, and we need MonteCarloMeasurements

Yep - should be quick. I'll do it now.

**Comment by cscherrer** [comment]
Excellent. Closing this now
