### ISSUE TITLE
Question: When creating a model, should the user instead specify a `prior` and `likelihood`?

### ISSUE THREAD

**Issue by DilumAluthge** [cscherrer/SossMLJ.jl#42]
Taken from:

https://github.com/cscherrer/SossMLJ.jl/blob/44a9882322e20e981eea799bd125fad71437fe30/src/SossMLJ.jl#L29-L44

**Comment by cscherrer** [comment]
Thanks, let's leave this one alone. At the time I thought it might have been hard to extract these from the model, but it seems to work out
