### ISSUE TITLE
TODO: Add an way to specify which variable is observed, and which is predicted

### ISSUE THREAD

**Issue by DilumAluthge** [cscherrer/SossMLJ.jl#43]
E.g. even if we observe `y`, we might sometimes prefer to predict `yhat`.

Taken from:

https://github.com/cscherrer/SossMLJ.jl/blob/44a9882322e20e981eea799bd125fad71437fe30/src/SossMLJ.jl#L29-L44

**Comment by cscherrer** [comment]
Right, maybe the model spec should include something like `response = :y` for a default, and `predict` should default to whatever was set in the original model. Does that sounds reasonable?

**Comment by DilumAluthge** [comment]
What is the difference between predicting `y` and predicting `yhat`?

**Comment by DilumAluthge** [comment]
So, looking at the example again, you have this:
```julia
yhat = X * β
y ~ For(eachindex(yhat)) do j
    Normal(yhat[j], σ)
end
```

Is this the same `y` and `yhat` that you are referring to?

This is the notation that I'm more familiar with is this: i.e. what you call `yhat` is what I would call `η`.
```julia
η = X * β
y ~ For(eachindex(η)) do j
    Normal(η[j], σ)
end
```

**Comment by cscherrer** [comment]
That's really interesting, are there texts that use η in this way? My only concern would be mistaking it for an n.

I'll admit yhat is a bit sloppy for this use, usually it means the predicted y value based on a parameter estimate.

**Comment by cscherrer** [comment]
Oh, and

> What is the difference between predicting y and predicting yhat?

`y` follows a distribution that depends on `yhat`. So `y` will have additional noise. Also, the type might be completely different. Like in logistic regression yhat is a probability and y is in {0,1}

**Comment by DilumAluthge** [comment]
Ahhh, okay now I figured out the notation.

I was wrong initially. `yhat` is not `η`.

What you call `yhat` is what I would call `μ`.

Here’s the notation that I’m familiar with for a GLM. This is what McCullagh and Nelder use.

My observations `y` are a realization of a random variable `Y`. I define `μ` as the expectation of `Y`, i.e. `μ := E[Y]`. My GLM consists of three components:
1. The probability distribution of `Y`. Classically, this distribution is a member of the exponential family, although there are ways to relax this restriction.
2. The linear predictor `η`, which I define as such: `η := Xβ`.
3. The link function `g`, which provides the following relationship: `g(μ) = g(E[Y]) = η = Xβ`

In the case of linear regression, `y` is normally distributed with mean `μ`. In linear regression, the link function is the identity function, so `μ` is equal to `η`.

In the case of binary logistic regression, `y` is Bernoulli distributed with mean `μ`. In logistic regression (and in general), `μ` is not equal to `η`.

So I guess what you call `yhat` is what I would call `μ`.

So I definitely agree with you that there are use cases for predicting both. As you said, in the logistic regression, `μ` will be our probabilities, so the components of `μ` will be real numbers between 0 and 1. But `y` will be classes, so the components of `y` will be integers that are each either `0` or `1`.

**Comment by DilumAluthge** [comment]
> Right, maybe the model spec should include something like response = :y for a default, and predict should default to whatever was set in the original model. Does that sounds reasonable?

This makes sense to me. So, when you specify the model, you can provide either `response = :y` or `response = :μ`. If the user does not specify, let us default to `response = :y`.

And then in `predict`, what if we have a keyword argument where the user can specify either `response = :y` or `response = :μ`. If the user specifies, then we will draw samples from the specified. But if the user does not specify, then we use whatever was specified when the model was defined.

**Comment by DilumAluthge** [comment]
> I'll admit yhat is a bit sloppy for this use, usually it means the predicted y value based on a parameter estimate.

Yeah this is what tripped me up 😂

**Comment by DilumAluthge** [comment]
> That's really interesting, are there texts that use η in this way? My only concern would be mistaking it for an n.

If we want, we could just spell them out, i.e. `mu` instead of `μ` and `eta` instead of `η`.

**Comment by cscherrer** [comment]
> And then in predict, what if we have a keyword argument where the user can specify either response = :y or response = :μ. If the user specifies, then we will draw samples from the specified. But if the user does not specify, then we use whatever was specified when the model was defined.

Much more general than this I think.... `y` will be common so it's a sensible default, but users can predict whatever they want in their model, so we can just let them pass a `Symbol`

**Comment by DilumAluthge** [comment]
> but users can predict whatever they want in their model, so we can just let them pass a `Symbol`

Perfect.

**Comment by DilumAluthge** [comment]
As far as prior art goes, I looked at GLM.jl, and the `GLM.predict` function returns `μ`. See for example the definition of `predict` here: https://github.com/JuliaStats/GLM.jl/blob/6a063f83bd51f63d7e8b2bcbc12247dfa09975de/src/glmfit.jl#L515-L532 (with an example definition of `linkinv` here: https://github.com/JuliaStats/GLM.jl/blob/6a063f83bd51f63d7e8b2bcbc12247dfa09975de/src/glmtools.jl#L232-L232)

I think that in general, the default `response = :y` is fine. But for GLMs, we should (in our examples) use `response = :μ`, to be consistent with GLM.jl.

This is what I've done in #64
