### ISSUE TITLE
Particles for posterior?

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/SossMLJ.jl#5]
It sometimes helps to represent the posterior in terms of particles (from `MonteCarloMeasurements.jl`):

```julia
julia> fr[2] |> Soss.particles
(θ = MonteCarloMeasurements.Particles{Float64,1000}[-0.449 ± 0.044, -0.68 ± 0.042, -0.816 ± 0.045, 0.031 ± 0.048, -0.201 ± 0.045, -0.454 ± 0.046, 0.76 ± 0.046, 1.37 ± 0.045, -0.27 ± 0.047, -2.19 ± 0.045],)
```

For prediction, these can be manipulated as if each `x ± sd` were a single number. This way we get some SIMD speed-up in prediction, and it makes it very easy to scan the results, relative to having an array result.

Just noting here in case we want to go this route

**Comment by tlienart** [comment]
what do these `sd` represent?

**Comment by cscherrer** [comment]
The printed representation is mean ± standard deviation
https://github.com/baggepinnen/MonteCarloMeasurements.jl

**Comment by cscherrer** [comment]
Closing this in favor of https://github.com/cscherrer/SossMLJ.jl/issues/37
