### ISSUE TITLE
"MultivariateFinite" distributions

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/SossMLJ.jl#65]
This issue concerns classification models. MLJ requires `Probabilistic` classification models to return a `Vector{UnivariateFinite}`. There's already some connection of this to `CategoricalArrays`:

```julia
julia> v = categorical([:x, :x, :y, :x, :z])
5-element CategoricalArray{Symbol,1,UInt32}:
 :x
 :x
 :y
 :x
 :z

julia> v[1]
CategoricalValue{Symbol,UInt32} :x

julia> d = MMI.UnivariateFinite(classes(v), [0.2, 0.3, 0.5])
UnivariateFinite{Multiclass{3}}(x=>0.2, y=>0.3, z=>0.5)

julia> rand(d)
CategoricalValue{Symbol,UInt32} :x
```

But I don't know of an existing way to sample a random `CategoricalArray`, for example, even in the iid case...

```julia
julia> rand(d,5)
5-element Array{Any,1}:
 CategoricalValue{Symbol,UInt32} :z
 CategoricalValue{Symbol,UInt32} :z
 CategoricalValue{Symbol,UInt32} :x
 CategoricalValue{Symbol,UInt32} :y
 CategoricalValue{Symbol,UInt32} :z
```

This might seem close enough, but redundancy in the representation makes it very inefficient:

```julia
julia> sizeof(v)
16

julia> sizeof(rand(d,5))
40
```

So, what we really need is a "MultivariateFinite" distribution, i.e., a multivariate distribution for which
- `rand` produces a `CategoricalArray`
- `marginalize` produces a `Vector{UnivariateFinite}`

We're already overloading `For` according to the type of the indices. Maybe for cases like this we should overload it based on the type of the distribution as well?

**Comment by DilumAluthge** [comment]
I think MLJ actually recommends `UnivariateFiniteVector` instead of `Vector{UnivariateFinite}`. I think the former is more efficient to construct.

**Comment by DilumAluthge** [comment]
So `marginalize` should construct and return a `UnivariableFiniteVector` in the efficient way.

Apart from that, everything else looks good to me

**Comment by cscherrer** [comment]
@DilumAluthge do you know of any docs or examples for `UnivariateFiniteVector`s?

**Comment by DilumAluthge** [comment]
Hmmm good question. 

Here's how they do it in MLJLinearModels: https://github.com/alan-turing-institute/MLJLinearModels.jl/blob/master/src/mlj/interface.jl

**Comment by DilumAluthge** [comment]
Signature looks something like `MMI.UnivariateFinite(classes, preds)`

**Comment by cscherrer** [comment]
But `UnivariateFinite` is just for a single value. I see this in `MLJBase`:

```julia
struct UnivariateFiniteArray{S,V,R,P,N} <: AbstractArray{UnivariateFinite{S,V,R,P},N}
    scitype::Type{S}
    decoder::CategoricalDecoder{V,R}
    prob_given_ref::LittleDict{R,Array{P,N},Vector{R}, Vector{Array{P,N}}}
end
```

but that's kind of awkward to build. I'll ask in an MLJ issue

**Comment by cscherrer** [comment]
@DilumAluthge and @ablaom got me straightened out on Slack. Just to note here...

```julia
julia> v = categorical([:x, :x, :y, :x, :z, :w])
6-element CategoricalArray{Symbol,1,UInt32}:
 :x
 :x
 :y
 :x
 :z
 :w

julia> probs = rand(100, 3);

julia> probs = probs ./ sum(probs, dims=2);

julia> ufvec = UnivariateFinite([:x, :y, :z], probs; pool=v.pool);
```

Then e.g., 
```julia
julia> ufvec[1:3]
3-element UnivariateFiniteArray{Multiclass{4},Symbol,UInt32,Float64,1}:
 UnivariateFinite{Multiclass{4}}(x=>0.394, y=>0.235, z=>0.37)
 UnivariateFinite{Multiclass{4}}(x=>0.115, y=>0.576, z=>0.309)
 UnivariateFinite{Multiclass{4}}(x=>0.301, y=>0.298, z=>0.401)

julia> rand.(ufvec[1:3])
3-element CategoricalArray{Symbol,1,UInt32}:
 :y
 :z
 :x
```

**Comment by DilumAluthge** [comment]
Want to add that to the open PR?

**Comment by ablaom** [comment]
@cscherrer Please close if this resolves your issue.

**Comment by cscherrer** [comment]
This gets us past the immediate issue. There's plenty more we can do with this, but I'll close this one. Thanks @ablaom @DilumAluthge
