### ISSUE TITLE
Extending `For` and `UnivariateFinite`

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/SossMLJ.jl#68]
In https://github.com/cscherrer/SossMLJ.jl/issues/65, @ablaom and @DilumAluthge helped clear up the use of `UnivariateFinite`

```julia
julia> v = categorical([:x, :x, :y, :x, :z, :w])
6-element CategoricalArray{Symbol,1,UInt32}:
 :x
 :x
 :y
 :x
 :z
 :w

julia> probs = rand(100, 3);

julia> probs = probs ./ sum(probs, dims=2);

julia> ufvec = UnivariateFinite([:x, :y, :z], probs; pool=v.pool);
```

The supertypes of `ufvec` and of each of its elements are

```julia
julia> supertypes(typeof(ufvec)) |> collect
3-element Array{DataType,1}:
 UnivariateFiniteArray{Multiclass{4},Symbol,UInt32,Float64,1}
 AbstractArray{UnivariateFinite{Multiclass{4},Symbol,UInt32,Float64},1}
 Any

julia> supertypes(typeof(ufvec[1])) |> collect
4-element Array{DataType,1}:
 UnivariateFinite{Multiclass{4},Symbol,UInt32,Float64}
 Distribution{Univariate,MLJBase.NonEuclidean}
 Sampleable{Univariate,MLJBase.NonEuclidean}
 Any
```

This is a great start, but there are still some problems to resolve...

### Not a distribution

Instead of a `Distribution{Vector}`, `ufvec` is a `Vector{Distribution}`. This makes it awkward to work with in a PPL context, where we need to express a joint distribution over all variables.

### No `logpdf` for elements

This works just fine:

```julia
julia> r = rand(ufvec[1])
CategoricalArrays.CategoricalValue{Symbol,UInt32} :y
```

But when we try to evaluate the `logpdf` on this value, things break:

```julia
julia> logpdf(ufvec[1], r)
ERROR: MethodError: no method matching logpdf(::UnivariateFinite{Multiclass{4},Symbol,UInt32,Float64}, ::CategoricalArrays.CategoricalValue{Symbol,UInt32})
Closest candidates are:
  logpdf(::Soss.SymDist, ::Any) at /home/chad/.julia/packages/Soss/FgRzp/src/symbolic/symbolic.jl:69
  logpdf(::Distribution{Univariate,S} where S<:ValueSupport, ::Real) at /home/chad/.julia/packages/Distributions/jFoHB/src/univariates.jl:342
  logpdf(::Distribution{Univariate,S} where S<:ValueSupport, ::AbstractArray) at deprecated.jl:70
```

It seems this might not have been defined?

### Log weights

First, it's often useful to work in terms of log-weights. This can get us more directly to the logpdf without a need to exponentiate and normalize.

### Idiomatic Soss

In Soss, the `For` combinator gives a flexible way to express multivariate distributions. We'd probably write something like

```julia
@model pool begin
    ...
    p ~ ...      # n×k matrix, each row a probability vector
    y ~ For(n) do j
         UnivariateFinite(pool, p[j, :]; pool=pool)
    end
end
```

We could maybe have the implementation optimize this by working in terms of a `UnivariateFiniteArray`, but the extra wrapping makes me wonder if this is really the right abstraction for this case.

Anyway, I'll need to think on this some more...

**Comment by DilumAluthge** [comment]
> This makes it awkward to work with in a PPL context, where we need to express a joint distribution over all variables.

Worst case, we still have `MMI.predict_joint`, which will output a joint distribution in the form of a single `SossMLJPredictor` object.

So worst case we can use that for most of our analyses, and only keep the `UnivariateFiniteVector` (output by `MMI.predict`) for compliance with the MLJ API.

**Comment by cscherrer** [comment]
Right, what I'm trying to work through is

- Users should be able to write `x ~ dist` for any `dist::Distribution`
- Results should be correct
- Inference should be fast
- Surprises should be minimized

So I just want to be careful with any rewriting we do. The weirdness is that it doesn't make sense to write `y ~ UnivariateFinite(...)` to produce a vector, because then it's not a distribution.

Oh, maybe instead of 

```julia
@model pool begin
    ...
    p ~ ...      # n×k matrix, each row a probability vector
    y ~ For(n) do j
         UnivariateFinite(pool, p[j, :]; pool=pool)
    end
end
```

users could write

```julia
@model pool begin
    ...
    p ~ ...      # n×k matrix, each row a probability vector
    uf = UnivariateFinite(pool, p; pool=pool)
    y ~ For(n) do j
        uf[j]         
    end
end
```

That looks a little weird, but I think it might work and preserve the semantics without any rewriting

**Comment by DilumAluthge** [comment]
I like that. It makes sense to me. `uf` is a vector of distributions, so `uf[j]` is a distribution, so you should be able to `~ uf[j]`

**Comment by cscherrer** [comment]
Ok this almost works:

```julia
julia> m = @model X,pool begin
           n = size(X,1)
           k = size(X,2)
           num_levels = length(pool.levels)
           β ~ Normal() |> iid(k,num_levels)
           p = mapslices(softmax, X*β; dims=2)
           
           ydists = UnivariateFinite(pool.levels, p; pool=pool)
           
           y ~ For(j -> ydists[j], n)
       end;

julia> X = randn(10,4);

julia> data = rand(m(X=X,pool=iris.Species.pool));

julia> pairs(data)
pairs(::NamedTuple) with 7 entries:
  :num_levels => 3
  :n          => 10
  :k          => 4
  :p          => [0.713189 0.221859 0.0649522; 0.593764 0.21153 0.194706; … ; 0.0496553 0.303406 0.646939; 0.326088 0.480961 0.192951]
  :ydists     => UnivariateFinite{Multiclass{3},String,UInt8,Float64}[UnivariateFinite{Multiclass{3}}(setosa=>0.713, versicolor=>0.222, virginica=>0.065), Univa…
  :β          => [-0.0979245 -1.54235 0.446163; -0.215617 1.07077 0.996174; -0.901628 -0.692875 0.275869; -0.22702 -0.647931 -1.31909]
  :y          => CategoricalValue{String,UInt8}["versicolor", "virginica", "versicolor", "setosa", "virginica", "setosa", "setosa", "setosa", "virginica", "vers…

julia> logpdf(m(X=X,pool=iris.Species.pool), data)
ERROR: MethodError: no method matching logpdf(::UnivariateFinite{Multiclass{3},String,UInt8,Float64}, ::CategoricalValue{String,UInt8})
```

@ablaom since this `<: Distribution`, is there a `logpdf` method somewhere? Maybe it's still a TODO?

**Comment by cscherrer** [comment]
Looks like it does have a `pdf` method, so getting to `logpdf` will be quick. It's a little surprising `logpdf` doesn't try to call `pdf` as a fallback.

**Comment by cscherrer** [comment]
Got it working! We should PR this somewhere:
```julia
Distributions.logpdf(d::UnivariateFinite, y::CategoricalValue)  = log(pdf(d, y))
```

It would be better to work in terms of log-probabilities, since we could avoid all the log/exp back-and-forthing. But let's put that off for now.

**Comment by DilumAluthge** [comment]
Can you make a PR to MLJBase? That's where the distribution lives.

**Comment by cscherrer** [comment]
Sounds good, thanks for the pointer.

Here's the current classification implementation:
https://github.com/cscherrer/SossMLJ.jl/blob/cs-dev/examples/example-classification.jl

**Comment by DilumAluthge** [comment]
Want to move the `softmax` and `softmax!` code into the SossMLJ source code itself? Maybe a file `src/softmax.jl`? I think enough people will use it for us to justify putting it in the package itself.

**Comment by cscherrer** [comment]
Yeah, or maybe in Soss, since this will come up there too. Or maybe it's already in another library? This is an edited version of the one from StatsFuns, since that wasn't AD-friendly. Maybe there's one in Flux or something?

**Comment by cscherrer** [comment]
Trying out NNlib...

**Comment by DilumAluthge** [comment]
The `NNlib` one is AD-able. I've used it with DynamicHMC with ForwardDiff.
