### ISSUE TITLE
Correlated predictions

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/SossMLJ.jl#7]
Context:
https://github.com/alan-turing-institute/MLJ.jl/issues/552

This is a very general thing to need to compute. For now, let's work in the context of a *Soss model* with inference based on *sampling form the posterior*.

Ok, so starting with

```julia
using Soss
using NNlib:softmax

m = @model X,numGroups begin
           numFeatures = size(X,2)
           β ~ Normal() |> iid(numFeatures, numGroups)
           p = softmax.(eachrow(X*β))
           y ~ For(eachindex(p)) do j
                   Categorical(p[j])
               end
       end
```

Let's generate some fake data to work with:

```julia
X = randn(10,4);
numGroups = 3;
truth = rand(m(X=X, numGroups=numGroups));
```

Just to be sure it's clear what these look like,

```julia
julia> pairs(truth)
pairs(::NamedTuple) with 4 entries:
  :numFeatures => 4
  :p           => [[0.662855, 0.097413, 0.239732], [0.0580695, 0.759806, 0.182125], [0.526723…
  :β           => [-0.170417 0.200644 0.792077; 1.04429 0.223441 -0.249901; -1.31362 0.840029…
  :y           => [1, 2, 1, 1, 1, 3, 3, 3, 3, 2]

julia> post = dynamicHMC(m(X=X,numGroups=k), (y=truth.y,));

julia> post[1:3]
3-element Array{NamedTuple{(:β,),Tuple{Array{Float64,2}}},1}:
 (β = [-0.08155179784663275 0.7216696063590625 -1.8711664252891904; 2.2718764364456945 0.44428137884960084 -0.8386157070286112; -0.02372191562715298 0.01310026155994326 -1.1304312702148538; -1.0650968874606566 -0.9635230623400672 0.714111509904722],)
 (β = [1.075592397470991 -0.10533221762796352 0.19727748726423927; 0.3865394478574915 0.006084358095325131 -2.0794641359423887; -0.08414585443537456 1.0826236025886116 0.10174623083035964; 0.6378566486860809 -0.8391680122795857 2.4398972242612014],)
 (β = [0.8769923643969655 0.22970199199065608 -0.05135033442750675; 0.44241237346878737 0.0955852142101039 -2.252828472692951; 0.29264573786629405 -0.20121257376012536 -0.7988963586434179; 0.5062012581257084 -0.7579678907483699 1.6974673707942554],)
```

Next, we ask Soss to build the predictive model:

```julia
julia> pred = predictive(m, :β)
@model (X, β) begin
        p = softmax.(eachrow(X * β))
        y ~ For(eachindex(p)) do j
                Categorical(p[j])
            end
    end
```

# `rand`

Abstractly, `pred` and `post` together form a distribution over response vectors. To draw randomly from this, we supply an `X` like this:

```julia
julia> rand(pred((X=X, rand(post)...))).y
10-element Array{Int64,1}:
 2
 1
 3
 3
 2
 2
 3
 3
 3
 2
```

# `logpdf`

Next, let's look at `logpdf`. The density at a given `y` is given by
![image](https://user-images.githubusercontent.com/1184449/89590562-0ba0b280-d7fd-11ea-9269-bc7489b9d44c.png)

We're approximating the posterior with a sample, so for `N` samples this is
![image](https://user-images.githubusercontent.com/1184449/89590638-3854ca00-d7fd-11ea-83fe-11422d496590.png)

But we want the `log` of this, so
![image](https://user-images.githubusercontent.com/1184449/89590701-62a68780-d7fd-11ea-9aa9-e23512337ed0.png)

And we don't have the probabilities but *log*-probabilities, so we'll need `logsumexp`:

```julia
julia> logsumexp([logpdf(pred((X=X, p...)), (y=truth.y,)) for p in post]) - log(length(post))
-3.2514987472569454
```

# Conclusion

- Use Soss to get `post` and `pred`
- We'll need a struct to carry these around together
- This struct will be `<: Distribution`
- `rand` and `logpdf` defined as above

cc: @DilumAluthge

**Comment by cscherrer** [comment]
Abstractly, "particles, plus a distribution conditional on particles" is just a mixture distribution. I don't think `Distributions.MixtureModel` is a good fit for this, but building an alternative isn't too bad (I do this in `mix.jl` in Soss).

It could make sense to make this a subtype of `AbstractMixtureModel`. But that only works when the prior is represented as a finite sample. I'd like to leave room for this to instead be represented as an iterator (or something similar).

**Comment by DilumAluthge** [comment]
> I'd like to leave room for this to instead be represented as an iterator (or something similar).

I think you could make this a subtype of `Distributions.Sampleable` and have it be an iterator.

**Comment by cscherrer** [comment]
> I think you could make this a subtype of `Distributions.Sampleable` and have it be an iterator.

Sorry I had missed this. I think there's two different potential iterators in play:

1. It could be possible to iterate over posterior samples, with each iteration returning a sample `y` for each `x` 
2. When we sample from the posterior, this could be held as an iterator

(These aren't mutually exclusive)

Benefits of (2):

- We don't have to wait for so many posterior samples to complete - Even one sample point from the posterior can be used to generate a prediction for each `y`.
- We can draw as many samples as we want, instead of being limited to the fixed set

But I think this is farther down the line - most samplers today return a Vector, so we can just start with that

**Comment by DilumAluthge** [comment]
> But I think this is farther down the line - most samplers today return a Vector, so we can just start with that

Agreed.

**Comment by DilumAluthge** [comment]
I think we've implemented this basic functionality now. It is in the `predict_joint` and `predict_particles` functions.
