### ISSUE TITLE
Better GitHub repository description

### ISSUE THREAD

**Issue by DilumAluthge** [cscherrer/SossMLJ.jl#79]
We're getting close to registering the package. Now is probably a good time to change the GitHub repository description.

**Comment by cscherrer** [comment]
Thanks for catching this. I've changed it to
> SossMLJ makes it easy to build MLJ machines from user-defined models from the Soss probabilistic programming language 

We can close this issue if you think this sounds ok

**Comment by DilumAluthge** [comment]
Perfect!
