### ISSUE TITLE
@reexport using Soss?

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/SossMLJ.jl#82]
@DilumAluthge Is it reasonable to expect users will want exported functions from Soss to be available? We could add a one-liner from [Reexport.jl](https://github.com/simonster/Reexport.jl), what do you think?

**Comment by DilumAluthge** [comment]
I agree.

**Comment by DilumAluthge** [comment]
We just need to remember: whenever we update the `[compat]` entry for `Soss`, we need to make a breaking release of `SossMLJ.jl`.

Just as an example, suppose that `SossMLJ.jl version 0.1.0` has the following:
```toml
[compat]
Soss = "1.0.0"
```

If we update the compat entry to be this:
```toml
[compat]
Soss = "2.0.0"
```

Then we would need to make a breaking release of `SossMLJ.jl`, i.e. `SossMLJ.jl version 0.2.0`.

This is totally fine. We just need to remember to do it.

**Comment by DilumAluthge** [comment]
This doesn't actually block 0.1.0.

**Comment by cscherrer** [comment]
> We just need to remember: whenever we update the `[compat]` entry for `Soss`, we need to make a breaking release of `SossMLJ.jl`.

This is the point of CompatHelper, right? Will that do it?

**Comment by DilumAluthge** [comment]
> > We just need to remember: whenever we update the `[compat]` entry for `Soss`, we need to make a breaking release of `SossMLJ.jl`.
> 
> This is the point of CompatHelper, right? Will that do it?

Well... kind of.

If you have
```toml
[compat]
Soss = "1"
```

Then CompatHelper will open a PR to bump that to:
```toml
[compat]
Soss = "1, 2"
```

For most dependencies, this is fine, but not for Soss, since we re-export it. The `[compat]` entry for `Soss` should only allow a single breaking release of Soss at any given time.
