### ISSUE TITLE
Branch protection settings for the `master` branch

### ISSUE THREAD

**Issue by DilumAluthge** [cscherrer/SossMLJ.jl#87]
It would be a good idea to add branch protection settings for the `master` branch, in order to keep us from accidentally making changes directly to `master`.

The following steps would be sufficient:

1. Go to https://github.com/cscherrer/SossMLJ.jl/settings/branches
2. Click on the "Add rule" button.
3. In the "Branch name pattern" box, enter `master`.
4. Check the "Require status checks to pass before merging" checkbox.
5. Check the "Require branches to be up to date before merging" checkbox. This ensures that we will never have any [semantic conflicts](https://bors.tech/essay/2017/02/02/pitch/).
6. In the "Status checks found in the last week for this repository" section, check all of the following checkboxes: 
    - [ ] "Documentation"
    - [ ] "Julia 1 - ubuntu-latest - x64 - pull_request"
    - [ ] "codecov/patch"
    - [ ] "codecov/project"
7. At the bottom of the page, click the green "Save changes" button.

**Comment by cscherrer** [comment]
Great idea, thanks!
