### ISSUE TITLE
GitHub repository settings: repo website

### ISSUE THREAD

**Issue by DilumAluthge** [cscherrer/SossMLJ.jl#89]
For better discoverability of the documentation, we should edit the GitHub repository settings to make this the website for the repo:
- https://cscherrer.github.io/SossMLJ.jl/stable/

The "stable" docs URL will not exist until after the first release of the package is registered and tagged. So this issue does not need to be tackled until after we have registered 0.1.0

**Comment by DilumAluthge** [comment]
@cscherrer You can go ahead and set the repo website to https://cscherrer.github.io/SossMLJ.jl/stable/

The package registration PR will be automatically merged in 3 days. Then, during the next TagBot cron job, the `0.1.0` tag will be automatically created, which will trigger the `stable` docs to build.

**Comment by cscherrer** [comment]
Done!
